# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Ragu Pappu
tagline:             'Technical thoughts, mostly'
description:         'Technical projects and notes by Ragu Pappu'
url:                 http://www.ragupappu.com/
baseurl:             /
paginate:            5

# Pages
pages:
  Archive: '/archive'
  About: '/about'
  Tags: '/tags'

# About/contact
author:
  name:              'Ragu Pappu'
  url:               http://www.ragupappu.com/

github:
  repo:              https://github.com/ragupappu/ragupappu.github.io

sass:
  sass_dir: _sass
  style: :compressed

# Theme
theme:

 # Localization Strings
 str_continue_reading: "Continue reading..."

# Custom vars
version:             1.0.4
